# Generated by Django 6.0.1 on 2026-01-10 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(db_column='fullName', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin')], default='admin', max_length=20)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.CharField(db_column='contractorId', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('current_rating', models.FloatField(db_column='currentRating', default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_complaints', models.IntegerField(db_column='totalComplaints', default=0)),
                ('total_projects', models.IntegerField(db_column='totalProjects', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'contractors',
            },
        ),
        migrations.CreateModel(
            name='RoadProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_id', models.CharField(db_column='roadId', max_length=255, unique=True)),
                ('road_name', models.CharField(db_column='roadName', max_length=255)),
                ('contractor_name', models.CharField(blank=True, db_column='contractorName', max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('construction_date', models.DateTimeField(db_column='constructionDate')),
                ('completion_date', models.DateTimeField(db_column='completionDate')),
                ('warranty_period_years', models.IntegerField(db_column='warrantyPeriodYears', default=10)),
                ('warranty_end_date', models.DateTimeField(blank=True, db_column='warrantyEndDate', null=True)),
                ('qr_code_data', models.TextField(blank=True, db_column='qrCodeData', null=True)),
                ('project_cost', models.DecimalField(blank=True, db_column='projectCost', decimal_places=2, max_digits=15, null=True)),
                ('road_length', models.DecimalField(blank=True, db_column='roadLength', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Under Maintenance', 'Under Maintenance')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contractor', models.ForeignKey(blank=True, db_column='contractorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.contractor')),
            ],
            options={
                'db_table': 'road_projects',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='userId', default='anonymous', max_length=255)),
                ('user_email', models.EmailField(blank=True, db_column='userEmail', max_length=254, null=True)),
                ('rating_value', models.FloatField(db_column='ratingValue', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contractor', models.ForeignKey(db_column='contractorId', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.contractor')),
                ('road', models.ForeignKey(blank=True, db_column='roadId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_ratings', to='api.roadproject')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(db_column='complaintId', max_length=255, unique=True)),
                ('user_id', models.CharField(db_column='userId', default='anonymous', max_length=255)),
                ('user_email', models.EmailField(blank=True, db_column='userEmail', max_length=254, null=True)),
                ('user_phone', models.CharField(blank=True, db_column='userPhone', max_length=20, null=True)),
                ('damage_type', models.CharField(choices=[('Pothole', 'Pothole'), ('Crack', 'Crack'), ('Erosion', 'Erosion'), ('Flooding', 'Flooding'), ('Other', 'Other')], db_column='damageType', max_length=50)),
                ('description', models.TextField()),
                ('photo_url', models.TextField(blank=True, db_column='photoUrl', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Open', max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('resolved_date', models.DateTimeField(blank=True, db_column='resolvedDate', null=True)),
                ('resolution_description', models.TextField(blank=True, db_column='resolutionDescription', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('road', models.ForeignKey(db_column='roadId', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.roadproject')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
