# Generated by Django 4.2.9 on 2026-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='qr_code',
            field=models.TextField(blank=True, db_column='qrCode', null=True),
        ),
    ]
